[project]
name = "giochetti"
version = "0.0.1"
description = "Simple gaming framework built on pyglet"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyglet>=2.1.12",
]

[dependency-groups]
dev = [
    "mypy ~= 1.9.0",
    "ruff >= 0.11.9,<0.12",
]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "FA", "I", "UP"]
